### ISSUE TITLE
Add zip function

### ISSUE THREAD

**Issue by shekhargulati** [shekhargulati/strman-java#72]

**Comment by Cs4r** [comment]
If you provide more details about this function I could implement it

**Comment by shekhargulati** [comment]
@Cs4r thanks for your help. This is what I want to implement

```java
zip("ABC","DEF")
// Result should be ["AD","BE","CF"]
```

**Comment by Cs4r** [comment]
What datatype should be the return type? List with two strings? A tuple? An array of length 2?

**Comment by shekhargulati** [comment]
@Cs4r it will be a `List<String>`. Rather than tuple it will be a String of length 2. Does this help?
