### ISSUE TITLE
Add formatNumber function

### ISSUE THREAD

**Issue by shekhargulati** [shekhargulati/strman-java#78]
The function will have following signature

```java
public static String formatNumber(long number)
public static String formatNumber(long number, NumberFormatOptions options)
```

Test cases it should pass:

```java
formatNumber(1000) // "1,000"
formatNumber(1000, NumberFormatOptions(2)) // "1000.00"
formatNumber(1000.754,NumberFormatOptions(0, "," , ".")) // "1.001"
formatNumber(1000000.754, NumberFormatIOptions(2, "," , ".")) // "1.000.000,75"
```

**Comment by ssshailesh28** [comment]
Please specify formatNumber(1000) //"1,000"
what about formatNumber(100000)=?
and formatNumber(10000000)=?
Also for formatOptions( ) NumberFormatOptions? 
please give more test cases?

**Comment by Cs4r** [comment]
Unfortunately this project has some issues underspecified and we cannot take over them without having to go back and forth with @shekhargulati :(

**Comment by flube2** [comment]
Would you still be interested in a pull request for this feature?

**Comment by ssshailesh28** [comment]
Yes I am. Please do let me know

**Comment by shekhargulati** [comment]
@ssshailesh28 @flube2 please submit the PR. I am not again PR. The point is we all discuss what should the function do.
