### ISSUE TITLE
Add lines function

### ISSUE THREAD

**Issue by shekhargulati** [shekhargulati/strman-java#83]
This function should have following signature

```java
public static String[] lines(String input)
```

Implementation should pass following test cases:

```java
assertEquals(lines("Hello\nWorld").length, 2);
assertEquals(lines("Hello\rWorld").length, 2);
assertEquals(lines("Hello World").length, 1);
assertEquals(lines("\r\n\n\r").length, 4);
assertEquals(lines("Hello\r\r\nWorld").length, 3);
assertEquals(lines("Hello\r\rWorld").length, 3);
assertEquals(lines(""), [""]);
assertEquals(lines(null), []);
assertEquals(lines("Hello\rWorld"), ["Hello", "World"]);
assertEquals(lines("Hello\r\nWorld"), ["Hello", "World"]);
```

**Comment by Cs4r** [comment]
It seems that your test cases are a bit limited so I do have a question: What should the method return in case of receiving a null string? Should it throw an exception or return an empty array?

**Comment by shekhargulati** [comment]
@Cs4r I plan to update the description to include all the test cases expected

**Comment by shekhargulati** [comment]
@Cs4r I have updated the issue. Can you pick this up now?

**Comment by Cs4r** [comment]
Yes, I will

**Comment by Cs4r** [comment]
Some test cases are ambiguous because you are mixing two kind of new line separators in here.  

- \n is used as an end-of-line terminator in Unix text files
- \r is used as an end-of-line terminator in Mac text files 
- \r\n are used to terminate lines in Windows and DOS text files

should the lines function accept an extra parameter that tells the user which sequence of characters will be used to define a new line separator?

**Comment by shekhargulati** [comment]
@Cs4r You are thinking too much. It just means you have to split when you find any of `\r`, `\n`, or `\r\n`. It has nothing to do with operating system.

**Comment by Cs4r** [comment]
I don't think so. If you find \r\n when would you split? There are several cases:

-You split when you find \r, then you split again when you find \n
- You split when you find \r\n

Depending on what you consider a new line separator you get one result or another

**Comment by Cs4r** [comment]
I know. Nevertheless you haven't replied to my questions yet. 

If you don't define well your specifications there is no room for collaboration.

**Comment by shekhargulati** [comment]
I didn't mean to say you don't know about String's regex method. Let me try to give answer to your question.

If we have String `Hello\r\nWorld` then we will split by `\r\n` together . If `\r\n` exists, we will only split by it.

I am not sure what is wrong with the specification. It clearly mentions all the cases this function should pass.

**Comment by Cs4r** [comment]
Ok... let's give you more examples so you notice what's wrong with the specs.

What should be the **output** for the following inputs:

`lines("Hello\r\r\nWorld")`
`lines("The\r\nquick\rbrown\nfox\r\njumps\nover\nthe\rlazy\rdog")`
